### ISSUE TITLE
Octokit resource not accessible by integration?

### ISSUE THREAD

**Issue by Nice3point** [Nice3point/RevitTemplates#38]
### Discussed in https://github.com/Nice3point/RevitTemplates/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **gaborschnierer** June 27, 2023</sup>
Hi @Nice3point!

Started a new solution using the solution template. Added a project using the Revit addin project template. Nuke local build runs perfectly. However, github action throws during PublishGitHub. Here is a snippet from the job log. Any suggestions?

```
  13:22:33 [INF] Tag: 1.0.0
  13:22:33 [INF] Changelog: D:\a\CleanN3P\CleanN3P\Changelog.md
  Error: Target "PublishGitHub" has thrown an exception
  13:22:33 [ERR] Target PublishGitHub has thrown an exception
  Octokit.ForbiddenException: Resource not accessible by integration
     at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 704
     at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 685
     at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
     at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 293
     at Build.CreatedDraftAsync(String gitHubOwner, String gitHubName, NewRelease newRelease) in D:\a\CleanN3P\CleanN3P\Build\Build.CI.GitHub.cs:line 50
     at Build.<get_PublishGitHub>b__5_5() in D:\a\CleanN3P\CleanN3P\Build\Build.CI.GitHub.cs:line 37
     at Nuke.Common.Execution.TargetDefinition.<>c__DisplayClass80_0.<Executes>b__0() in /_/source/Nuke.Build/Execution/TargetDefinition.cs:line 73
     at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
  {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release"}
```
</div>

**Comment by Nice3point** [comment]
@gaborschnierer https://github.com/Nice3point/RevitTemplates/issues/36 same issue ?
